theme: jekyll-theme-architect
title: Conor's homepage
description: Just testing out github pages with jekyll-theme-minimal, jekyll-theme-architect

Architect
Cayman
Dinky
Hacker
Leap day
Merlot
Midnight
Minima
Minimal
Modernist
Slate
Tactile
Time machine
